#!/bin/sh
# postrm script for bongosec-agent
# Bongosec, Inc 2015

set -e

DIR="/var/ossec"
BONGOSEC_TMP_DIR="${DIR}/packages_files/agent_config_files"

case "$1" in
    remove|failed-upgrade|abort-install|abort-upgrade|disappear)

        if [ -d ${BONGOSEC_TMP_DIR} ]; then
            rm -rf ${BONGOSEC_TMP_DIR}
        fi

        # Back up the old configuration files as .save
        if [ ! -d ${DIR}/etc ]; then
            mkdir -p ${DIR}/etc
        fi

        # If the directory is not empty, copy the files into ${DIR}/etc
        if ls -A ${DIR}/tmp/conffiles > /dev/null 2>&1 ; then
            mv ${DIR}/tmp/conffiles/* ${DIR}/etc
        fi
        rm -rf ${DIR}/tmp
        if [ "$1" = "remove" ]; then
            rm -rf ${DIR}/ruleset
            rm -rf ${DIR}/var
            rm -rf ${DIR}/logs
        fi

        # Delete old .save
        find ${DIR}/etc/ -type f  -name "*save" -exec rm -f {} \;

        # Rename the files
        find ${DIR}/etc/ -type f -exec mv {} {}.save \;

        ;;

        purge)

        if getent passwd bongosec >/dev/null 2>&1; then
            deluser bongosec > /dev/null 2>&1
        fi
        if getent group bongosec >/dev/null 2>&1; then
            delgroup bongosec > /dev/null 2>&1
        fi
        rm -rf ${DIR}/*

    ;;

    upgrade)

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

    ;;

esac

exit 0
